/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boletin_26;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author igonzalezcastro
 */
public class Bonoloto extends javax.swing.JFrame {

    static int CONTADOR=0;
     ArrayList<Integer> Seleccionados = new ArrayList<Integer>();
     ArrayList<Integer> Aleatorios = new ArrayList<Integer>();
     
    public Bonoloto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton41 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton10 = new javax.swing.JButton();
        boton11 = new javax.swing.JButton();
        boton12 = new javax.swing.JButton();
        boton13 = new javax.swing.JButton();
        boton14 = new javax.swing.JButton();
        boton15 = new javax.swing.JButton();
        boton16 = new javax.swing.JButton();
        boton17 = new javax.swing.JButton();
        boton18 = new javax.swing.JButton();
        boton19 = new javax.swing.JButton();
        boton20 = new javax.swing.JButton();
        boton21 = new javax.swing.JButton();
        boton22 = new javax.swing.JButton();
        boton23 = new javax.swing.JButton();
        boton24 = new javax.swing.JButton();
        boton25 = new javax.swing.JButton();
        boton26 = new javax.swing.JButton();
        boton27 = new javax.swing.JButton();
        boton28 = new javax.swing.JButton();
        boton29 = new javax.swing.JButton();
        boton30 = new javax.swing.JButton();
        boton31 = new javax.swing.JButton();
        boton32 = new javax.swing.JButton();
        boton33 = new javax.swing.JButton();
        boton34 = new javax.swing.JButton();
        boton35 = new javax.swing.JButton();
        boton36 = new javax.swing.JButton();
        boton37 = new javax.swing.JButton();
        boton38 = new javax.swing.JButton();
        boton39 = new javax.swing.JButton();
        boton40 = new javax.swing.JButton();
        boton41 = new javax.swing.JButton();
        boton42 = new javax.swing.JButton();
        boton43 = new javax.swing.JButton();
        boton44 = new javax.swing.JButton();
        boton45 = new javax.swing.JButton();
        boton46 = new javax.swing.JButton();
        boton47 = new javax.swing.JButton();
        boton48 = new javax.swing.JButton();
        boton49 = new javax.swing.JButton();
        etiqueta1 = new javax.swing.JTextField();
        Xenerar = new javax.swing.JButton();
        etiqueta2 = new javax.swing.JTextField();
        Validar = new javax.swing.JButton();
        Desmarcar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton41.setText("jButton41");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boton1.setBackground(new java.awt.Color(51, 204, 0));
        boton1.setForeground(new java.awt.Color(255, 255, 0));
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setBackground(new java.awt.Color(51, 204, 0));
        boton2.setForeground(new java.awt.Color(255, 255, 0));
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setBackground(new java.awt.Color(51, 204, 0));
        boton3.setForeground(new java.awt.Color(255, 255, 0));
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        boton4.setBackground(new java.awt.Color(51, 204, 0));
        boton4.setForeground(new java.awt.Color(255, 255, 0));
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton5.setBackground(new java.awt.Color(51, 204, 0));
        boton5.setForeground(new java.awt.Color(255, 255, 0));
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        boton6.setBackground(new java.awt.Color(51, 204, 0));
        boton6.setForeground(new java.awt.Color(255, 255, 0));
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        boton7.setBackground(new java.awt.Color(51, 204, 0));
        boton7.setForeground(new java.awt.Color(255, 255, 0));
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton8.setBackground(new java.awt.Color(51, 204, 0));
        boton8.setForeground(new java.awt.Color(255, 255, 0));
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        boton9.setBackground(new java.awt.Color(51, 204, 0));
        boton9.setForeground(new java.awt.Color(255, 255, 0));
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton10.setBackground(new java.awt.Color(51, 204, 0));
        boton10.setForeground(new java.awt.Color(255, 255, 0));
        boton10.setText("10");
        boton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton10ActionPerformed(evt);
            }
        });

        boton11.setBackground(new java.awt.Color(51, 204, 0));
        boton11.setForeground(new java.awt.Color(255, 255, 0));
        boton11.setText("11");
        boton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton11ActionPerformed(evt);
            }
        });

        boton12.setBackground(new java.awt.Color(51, 204, 0));
        boton12.setForeground(new java.awt.Color(255, 255, 0));
        boton12.setText("12");
        boton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton12ActionPerformed(evt);
            }
        });

        boton13.setBackground(new java.awt.Color(51, 204, 0));
        boton13.setForeground(new java.awt.Color(255, 255, 0));
        boton13.setText("13");
        boton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton13ActionPerformed(evt);
            }
        });

        boton14.setBackground(new java.awt.Color(51, 204, 0));
        boton14.setForeground(new java.awt.Color(255, 255, 0));
        boton14.setText("14");
        boton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton14ActionPerformed(evt);
            }
        });

        boton15.setBackground(new java.awt.Color(51, 204, 0));
        boton15.setForeground(new java.awt.Color(255, 255, 0));
        boton15.setText("15");
        boton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton15ActionPerformed(evt);
            }
        });

        boton16.setBackground(new java.awt.Color(51, 204, 0));
        boton16.setForeground(new java.awt.Color(255, 255, 0));
        boton16.setText("16");
        boton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton16ActionPerformed(evt);
            }
        });

        boton17.setBackground(new java.awt.Color(51, 204, 0));
        boton17.setForeground(new java.awt.Color(255, 255, 0));
        boton17.setText("17");
        boton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton17ActionPerformed(evt);
            }
        });

        boton18.setBackground(new java.awt.Color(51, 204, 0));
        boton18.setForeground(new java.awt.Color(255, 255, 0));
        boton18.setText("18");
        boton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton18ActionPerformed(evt);
            }
        });

        boton19.setBackground(new java.awt.Color(51, 204, 0));
        boton19.setForeground(new java.awt.Color(255, 255, 0));
        boton19.setText("19");
        boton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton19ActionPerformed(evt);
            }
        });

        boton20.setBackground(new java.awt.Color(51, 204, 0));
        boton20.setForeground(new java.awt.Color(255, 255, 0));
        boton20.setText("20");
        boton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton20ActionPerformed(evt);
            }
        });

        boton21.setBackground(new java.awt.Color(51, 204, 0));
        boton21.setForeground(new java.awt.Color(255, 255, 0));
        boton21.setText("21");
        boton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton21ActionPerformed(evt);
            }
        });

        boton22.setBackground(new java.awt.Color(51, 204, 0));
        boton22.setForeground(new java.awt.Color(255, 255, 0));
        boton22.setText("22");
        boton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton22ActionPerformed(evt);
            }
        });

        boton23.setBackground(new java.awt.Color(51, 204, 0));
        boton23.setForeground(new java.awt.Color(255, 255, 0));
        boton23.setText("23");
        boton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton23ActionPerformed(evt);
            }
        });

        boton24.setBackground(new java.awt.Color(51, 204, 0));
        boton24.setForeground(new java.awt.Color(255, 255, 0));
        boton24.setText("24");
        boton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton24ActionPerformed(evt);
            }
        });

        boton25.setBackground(new java.awt.Color(51, 204, 0));
        boton25.setForeground(new java.awt.Color(255, 255, 0));
        boton25.setText("25");
        boton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton25ActionPerformed(evt);
            }
        });

        boton26.setBackground(new java.awt.Color(51, 204, 0));
        boton26.setForeground(new java.awt.Color(255, 255, 0));
        boton26.setText("26");
        boton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton26ActionPerformed(evt);
            }
        });

        boton27.setBackground(new java.awt.Color(51, 204, 0));
        boton27.setForeground(new java.awt.Color(255, 255, 0));
        boton27.setText("27");
        boton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton27ActionPerformed(evt);
            }
        });

        boton28.setBackground(new java.awt.Color(51, 204, 0));
        boton28.setForeground(new java.awt.Color(255, 255, 0));
        boton28.setText("28");
        boton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton28ActionPerformed(evt);
            }
        });

        boton29.setBackground(new java.awt.Color(51, 204, 0));
        boton29.setForeground(new java.awt.Color(255, 255, 0));
        boton29.setText("29");
        boton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton29ActionPerformed(evt);
            }
        });

        boton30.setBackground(new java.awt.Color(51, 204, 0));
        boton30.setForeground(new java.awt.Color(255, 255, 0));
        boton30.setText("30");
        boton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton30ActionPerformed(evt);
            }
        });

        boton31.setBackground(new java.awt.Color(51, 204, 0));
        boton31.setForeground(new java.awt.Color(255, 255, 0));
        boton31.setText("31");
        boton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton31ActionPerformed(evt);
            }
        });

        boton32.setBackground(new java.awt.Color(51, 204, 0));
        boton32.setForeground(new java.awt.Color(255, 255, 0));
        boton32.setText("32");
        boton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton32ActionPerformed(evt);
            }
        });

        boton33.setBackground(new java.awt.Color(51, 204, 0));
        boton33.setForeground(new java.awt.Color(255, 255, 0));
        boton33.setText("33");
        boton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton33ActionPerformed(evt);
            }
        });

        boton34.setBackground(new java.awt.Color(51, 204, 0));
        boton34.setForeground(new java.awt.Color(255, 255, 0));
        boton34.setText("34");
        boton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton34ActionPerformed(evt);
            }
        });

        boton35.setBackground(new java.awt.Color(51, 204, 0));
        boton35.setForeground(new java.awt.Color(255, 255, 0));
        boton35.setText("35");
        boton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton35ActionPerformed(evt);
            }
        });

        boton36.setBackground(new java.awt.Color(51, 204, 0));
        boton36.setForeground(new java.awt.Color(255, 255, 0));
        boton36.setText("36");
        boton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton36ActionPerformed(evt);
            }
        });

        boton37.setBackground(new java.awt.Color(51, 204, 0));
        boton37.setForeground(new java.awt.Color(255, 255, 0));
        boton37.setText("37");
        boton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton37ActionPerformed(evt);
            }
        });

        boton38.setBackground(new java.awt.Color(51, 204, 0));
        boton38.setForeground(new java.awt.Color(255, 255, 0));
        boton38.setText("38");
        boton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton38ActionPerformed(evt);
            }
        });

        boton39.setBackground(new java.awt.Color(51, 204, 0));
        boton39.setForeground(new java.awt.Color(255, 255, 0));
        boton39.setText("39");
        boton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton39ActionPerformed(evt);
            }
        });

        boton40.setBackground(new java.awt.Color(51, 204, 0));
        boton40.setForeground(new java.awt.Color(255, 255, 0));
        boton40.setText("40");
        boton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton40ActionPerformed(evt);
            }
        });

        boton41.setBackground(new java.awt.Color(51, 204, 0));
        boton41.setForeground(new java.awt.Color(255, 255, 0));
        boton41.setText("41");
        boton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton41ActionPerformed(evt);
            }
        });

        boton42.setBackground(new java.awt.Color(51, 204, 0));
        boton42.setForeground(new java.awt.Color(255, 255, 0));
        boton42.setText("42");
        boton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton42ActionPerformed(evt);
            }
        });

        boton43.setBackground(new java.awt.Color(51, 204, 0));
        boton43.setForeground(new java.awt.Color(255, 255, 0));
        boton43.setText("43");
        boton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton43ActionPerformed(evt);
            }
        });

        boton44.setBackground(new java.awt.Color(51, 204, 0));
        boton44.setForeground(new java.awt.Color(255, 255, 0));
        boton44.setText("44");
        boton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton44ActionPerformed(evt);
            }
        });

        boton45.setBackground(new java.awt.Color(51, 204, 0));
        boton45.setForeground(new java.awt.Color(255, 255, 0));
        boton45.setText("45");
        boton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton45ActionPerformed(evt);
            }
        });

        boton46.setBackground(new java.awt.Color(51, 204, 0));
        boton46.setForeground(new java.awt.Color(255, 255, 0));
        boton46.setText("46");
        boton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton46ActionPerformed(evt);
            }
        });

        boton47.setBackground(new java.awt.Color(51, 204, 0));
        boton47.setForeground(new java.awt.Color(255, 255, 0));
        boton47.setText("47");
        boton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton47ActionPerformed(evt);
            }
        });

        boton48.setBackground(new java.awt.Color(51, 204, 0));
        boton48.setForeground(new java.awt.Color(255, 255, 0));
        boton48.setText("48");
        boton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton48ActionPerformed(evt);
            }
        });

        boton49.setBackground(new java.awt.Color(51, 204, 0));
        boton49.setForeground(new java.awt.Color(255, 255, 0));
        boton49.setText("49");
        boton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton49ActionPerformed(evt);
            }
        });

        etiqueta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiqueta1ActionPerformed(evt);
            }
        });

        Xenerar.setBackground(new java.awt.Color(0, 204, 0));
        Xenerar.setForeground(new java.awt.Color(255, 255, 0));
        Xenerar.setText("Xenerar");
        Xenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XenerarActionPerformed(evt);
            }
        });

        Validar.setBackground(new java.awt.Color(0, 51, 255));
        Validar.setForeground(new java.awt.Color(255, 255, 0));
        Validar.setText("Validar");
        Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarActionPerformed(evt);
            }
        });

        Desmarcar.setBackground(new java.awt.Color(255, 0, 0));
        Desmarcar.setForeground(new java.awt.Color(255, 255, 0));
        Desmarcar.setText("Desmarcar");
        Desmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesmarcarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("¡Buena Suerte!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqueta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Xenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Validar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Desmarcar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton28, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton35, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton36, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(boton37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boton43, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addComponent(boton44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(boton49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Xenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Validar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Desmarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton1)
                    .addComponent(boton8)
                    .addComponent(boton15)
                    .addComponent(boton22)
                    .addComponent(boton29)
                    .addComponent(boton36)
                    .addComponent(boton43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton2)
                    .addComponent(boton9)
                    .addComponent(boton16)
                    .addComponent(boton23)
                    .addComponent(boton30)
                    .addComponent(boton37)
                    .addComponent(boton44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton3)
                    .addComponent(boton10)
                    .addComponent(boton17)
                    .addComponent(boton24)
                    .addComponent(boton31)
                    .addComponent(boton38)
                    .addComponent(boton45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton4)
                    .addComponent(boton11)
                    .addComponent(boton18)
                    .addComponent(boton25)
                    .addComponent(boton32)
                    .addComponent(boton39)
                    .addComponent(boton46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton5)
                    .addComponent(boton12)
                    .addComponent(boton19)
                    .addComponent(boton26)
                    .addComponent(boton33)
                    .addComponent(boton40)
                    .addComponent(boton47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton6)
                    .addComponent(boton13)
                    .addComponent(boton20)
                    .addComponent(boton27)
                    .addComponent(boton34)
                    .addComponent(boton41)
                    .addComponent(boton48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton7)
                    .addComponent(boton14)
                    .addComponent(boton21)
                    .addComponent(boton28)
                    .addComponent(boton35)
                    .addComponent(boton42)
                    .addComponent(boton49))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiqueta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiqueta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiqueta1ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        botones(boton1); 
         Seleccionados.add(1);CONTADOR++;
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
      botones(boton2);  CONTADOR++;
       Seleccionados.add(2);CONTADOR++;
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
      botones(boton3);  CONTADOR++;   
       Seleccionados.add(3);CONTADOR++;// TODO add your handling code here:
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
         botones(boton4);  CONTADOR++;
          Seleccionados.add(4);CONTADOR++;
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
         botones(boton5);  CONTADOR++;
          Seleccionados.add(5);CONTADOR++;
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
         botones(boton6);  CONTADOR++;
          Seleccionados.add(6);CONTADOR++;
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
         botones(boton7);  CONTADOR++;
          Seleccionados.add(7);CONTADOR++;
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
                 botones(boton8);  CONTADOR++;
                  Seleccionados.add(8);CONTADOR++;
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        botones(boton9);  CONTADOR++;
         Seleccionados.add(9);CONTADOR++;
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton10ActionPerformed
        botones(boton10);  CONTADOR++;
         Seleccionados.add(10);CONTADOR++;
    }//GEN-LAST:event_boton10ActionPerformed

    private void boton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton11ActionPerformed
        botones(boton11);  CONTADOR++;
         Seleccionados.add(11);CONTADOR++;
    }//GEN-LAST:event_boton11ActionPerformed

    private void boton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton12ActionPerformed
        botones(boton12);  CONTADOR++;
    }//GEN-LAST:event_boton12ActionPerformed

    private void boton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton13ActionPerformed
        botones(boton13);  CONTADOR++;
    }//GEN-LAST:event_boton13ActionPerformed

    private void boton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton14ActionPerformed
        botones(boton14);  CONTADOR++;
    }//GEN-LAST:event_boton14ActionPerformed

    private void boton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton15ActionPerformed
       botones(boton15);  CONTADOR++;
    }//GEN-LAST:event_boton15ActionPerformed

    private void boton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton16ActionPerformed
       botones(boton16);  CONTADOR++;
    }//GEN-LAST:event_boton16ActionPerformed

    private void boton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton17ActionPerformed
        botones(boton17);  CONTADOR++;
    }//GEN-LAST:event_boton17ActionPerformed

    private void boton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton18ActionPerformed
        botones(boton18);  CONTADOR++;
    }//GEN-LAST:event_boton18ActionPerformed

    private void boton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton19ActionPerformed
      botones(boton19);  CONTADOR++;
    }//GEN-LAST:event_boton19ActionPerformed

    private void boton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton20ActionPerformed
        botones(boton20);  CONTADOR++;
    }//GEN-LAST:event_boton20ActionPerformed

    private void boton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton21ActionPerformed
       botones(boton21);  CONTADOR++;
    }//GEN-LAST:event_boton21ActionPerformed

    private void boton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton22ActionPerformed
      botones(boton22);  CONTADOR++;
    }//GEN-LAST:event_boton22ActionPerformed

    private void boton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton23ActionPerformed
       botones(boton23);  CONTADOR++;
    }//GEN-LAST:event_boton23ActionPerformed

    private void boton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton24ActionPerformed
        botones(boton24);  CONTADOR++;
    }//GEN-LAST:event_boton24ActionPerformed

    private void boton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton25ActionPerformed
       botones(boton25);  CONTADOR++;
    }//GEN-LAST:event_boton25ActionPerformed

    private void boton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton26ActionPerformed
       botones(boton26);  CONTADOR++;
    }//GEN-LAST:event_boton26ActionPerformed

    private void boton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton27ActionPerformed
      botones(boton27);  CONTADOR++;
    }//GEN-LAST:event_boton27ActionPerformed

    private void boton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton28ActionPerformed
      botones(boton28);  CONTADOR++;
    }//GEN-LAST:event_boton28ActionPerformed

    private void boton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton29ActionPerformed
      botones(boton29);  CONTADOR++;
    }//GEN-LAST:event_boton29ActionPerformed

    private void boton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton30ActionPerformed
      botones(boton30);  CONTADOR++;
    }//GEN-LAST:event_boton30ActionPerformed

    private void boton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton31ActionPerformed
      botones(boton31);  CONTADOR++;
    }//GEN-LAST:event_boton31ActionPerformed

    private void boton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton32ActionPerformed
      botones(boton32);  CONTADOR++;
    }//GEN-LAST:event_boton32ActionPerformed

    private void boton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton33ActionPerformed
        botones(boton33);  CONTADOR++;
    }//GEN-LAST:event_boton33ActionPerformed

    private void boton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton34ActionPerformed
     botones(boton34);  CONTADOR++;
    }//GEN-LAST:event_boton34ActionPerformed

    private void boton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton35ActionPerformed
     botones(boton35);  CONTADOR++;
    }//GEN-LAST:event_boton35ActionPerformed

    private void boton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton36ActionPerformed
     botones(boton36);  CONTADOR++;
    }//GEN-LAST:event_boton36ActionPerformed

    private void boton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton37ActionPerformed
     botones(boton37);  CONTADOR++;
    }//GEN-LAST:event_boton37ActionPerformed

    private void boton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton38ActionPerformed
     botones(boton38);  CONTADOR++;
    }//GEN-LAST:event_boton38ActionPerformed

    private void boton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton39ActionPerformed
     botones(boton39);  CONTADOR++;
    }//GEN-LAST:event_boton39ActionPerformed

    private void boton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton40ActionPerformed
     botones(boton40);  CONTADOR++;
    }//GEN-LAST:event_boton40ActionPerformed

    private void boton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton41ActionPerformed
     botones(jButton41);  CONTADOR++;
    }//GEN-LAST:event_boton41ActionPerformed

    private void boton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton42ActionPerformed
     botones(boton41);  CONTADOR++;
    }//GEN-LAST:event_boton42ActionPerformed

    private void boton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton43ActionPerformed
    botones(boton42);  CONTADOR++;
    }//GEN-LAST:event_boton43ActionPerformed

    private void boton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton44ActionPerformed
     botones(boton43);  CONTADOR++;
    }//GEN-LAST:event_boton44ActionPerformed

    private void boton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton45ActionPerformed
       botones(boton44);  CONTADOR++;
    }//GEN-LAST:event_boton45ActionPerformed

    private void boton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton46ActionPerformed
      botones(boton45);  CONTADOR++;
    }//GEN-LAST:event_boton46ActionPerformed

    private void boton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton49ActionPerformed
      botones(boton48
      );  CONTADOR++;
    }//GEN-LAST:event_boton49ActionPerformed

    private void boton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton47ActionPerformed
       botones(boton46);  CONTADOR++;
    }//GEN-LAST:event_boton47ActionPerformed

    private void boton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton48ActionPerformed
     botones(boton47);  CONTADOR++;
    }//GEN-LAST:event_boton48ActionPerformed

    private void XenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XenerarActionPerformed
      aleatorio(Xenerar);
        for(int i=0;i<Aleatorios.size();i++){
       etiqueta2.setText(etiqueta2.getText()+"  "+Aleatorios.get(i));}
    }//GEN-LAST:event_XenerarActionPerformed

    private void ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarActionPerformed
        JButton validar = null;
       comparar(validar);
    }//GEN-LAST:event_ValidarActionPerformed

    private void DesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesmarcarActionPerformed
     desmarcar(boton1);desmarcar(boton2);desmarcar(boton3);
       desmarcar(boton4);desmarcar(boton5);desmarcar(boton6);
       desmarcar(boton7);desmarcar(boton8);desmarcar(boton9);
       desmarcar(boton10);desmarcar(boton11);desmarcar(boton12);
       desmarcar(boton13);desmarcar(boton14);desmarcar(boton15);
       desmarcar(boton16);desmarcar(boton17);desmarcar(boton18);
       desmarcar(boton19);desmarcar(boton20);desmarcar(boton21);
       desmarcar(boton22);desmarcar(boton23);desmarcar(boton24);
       desmarcar(boton25);desmarcar(boton26);desmarcar(boton27);
       desmarcar(boton28);desmarcar(boton29);desmarcar(boton30);
       desmarcar(boton31);desmarcar(boton32);desmarcar(boton33);
       desmarcar(boton34);desmarcar(boton35);desmarcar(boton36);
       desmarcar(boton37);desmarcar(boton38);desmarcar(boton39);
       desmarcar(boton40);desmarcar(jButton41);desmarcar(boton41);
       desmarcar(boton42);desmarcar(boton43);desmarcar(boton44);
       desmarcar(boton45);desmarcar(boton46);desmarcar(boton47);
       desmarcar(boton48);
    }//GEN-LAST:event_DesmarcarActionPerformed
public void botones(JButton boton){
    if(CONTADOR<6){
boton.setEnabled(false);

etiqueta1.setText(etiqueta1.getText()+boton.getText()+"   "); }
   }
    
public void aleatorio(JButton Xerar){
     
        int valores;
       
        for(int i = 0;i<6;i++){
            valores = (int) Math.floor(Math.random() * 49 )+1;
            while(Aleatorios.contains(valores)){
                valores = (int) Math.floor(Math.random() * 49 )+1;
            }
            Aleatorios.add(valores);
        }
}
public void desmarcar(JButton Desmarcar){
     Desmarcar.setEnabled(true);
     etiqueta1.setText("");
     etiqueta2.setText("");
     Seleccionados.removeAll(Seleccionados);
     Aleatorios.removeAll(Aleatorios);
     CONTADOR=0;
     
}
 
    

    public void comparar(JButton validar){
        if(Seleccionados.equals(Aleatorios)){
            JOptionPane.showMessageDialog(null,"PREMIO");
        }
        else
            JOptionPane.showMessageDialog(null,"MALA SUERTE");
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bonoloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desmarcar;
    private javax.swing.JButton Validar;
    private javax.swing.JButton Xenerar;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton10;
    private javax.swing.JButton boton11;
    private javax.swing.JButton boton12;
    private javax.swing.JButton boton13;
    private javax.swing.JButton boton14;
    private javax.swing.JButton boton15;
    private javax.swing.JButton boton16;
    private javax.swing.JButton boton17;
    private javax.swing.JButton boton18;
    private javax.swing.JButton boton19;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton20;
    private javax.swing.JButton boton21;
    private javax.swing.JButton boton22;
    private javax.swing.JButton boton23;
    private javax.swing.JButton boton24;
    private javax.swing.JButton boton25;
    private javax.swing.JButton boton26;
    private javax.swing.JButton boton27;
    private javax.swing.JButton boton28;
    private javax.swing.JButton boton29;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton30;
    private javax.swing.JButton boton31;
    private javax.swing.JButton boton32;
    private javax.swing.JButton boton33;
    private javax.swing.JButton boton34;
    private javax.swing.JButton boton35;
    private javax.swing.JButton boton36;
    private javax.swing.JButton boton37;
    private javax.swing.JButton boton38;
    private javax.swing.JButton boton39;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton40;
    private javax.swing.JButton boton41;
    private javax.swing.JButton boton42;
    private javax.swing.JButton boton43;
    private javax.swing.JButton boton44;
    private javax.swing.JButton boton45;
    private javax.swing.JButton boton46;
    private javax.swing.JButton boton47;
    private javax.swing.JButton boton48;
    private javax.swing.JButton boton49;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JTextField etiqueta1;
    private javax.swing.JTextField etiqueta2;
    private javax.swing.JButton jButton41;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
